name: workflow-ci
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - scikit-learn=1.3.2
  - pandas>=1.5
  - numpy>=1.24
  - pyyaml
  - matplotlib
  - pip:
    - mlflow>=2.14.0
    - dagshub 
    - cloudpickle==2.2.1