name: 3. CI Model Training

on:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Siapkan environment Conda
      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          activate-environment: workflow-ci
          environment-file: conda.yaml 
          python-version: '3.10'
          
      # Jalankan MLflow Project
      - name: Run MLflow Project
        shell: bash -l {0} 
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.DAGSHUB_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_PASSWORD }}
        working-directory: ./MLProject 
        run: |
          # Gunakan --env-manager local agar memakai env 'workflow-ci' yang sudah aktif
          mlflow run . --env-manager local
          
      - name: Build and Push Docker Image
        shell: bash -l {0}
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.DAGSHUB_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_PASSWORD }}

        run: |
          BEST_MODEL="./MLProject/saved_models/RF_Run_1"
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/pcos-model:$(date +%s)"
          
          mlflow models build-docker -m "$BEST_MODEL" -n "$IMAGE_NAME"
          docker push "$IMAGE_NAME"

          echo "--- Menyimpan nama image untuk langkah selanjutnya (jika ada) ---"
          echo "$IMAGE_NAME" > image_name.txt
