name: 3. CI Model Training

on:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Siapkan environment Conda
      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          
          activate-environment: workflow-ci
          
          environment-file: conda.yaml
          python-version: '3.10'
          
      # Jalankan MLflow Project
      - name: Run MLflow Project
        shell: bash -l {0} 
        
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.DAGSHUB_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_PASSWORD }}
          
        run: |
          mlflow run MLProject . --no-conda

      - name: Build and Push Docker Image
        shell: bash -l {0}
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.DAGSHUB_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_PASSWORD }}

        run: |
          echo "--- Logging in to Docker Hub ---"
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

          echo "--- Reading Run ID ---"
          export LATEST_RUN_ID=$(cat run_id.txt)
          echo "Menggunakan Run ID: $LATEST_RUN_ID"
          export MODEL_URI="runs:/$LATEST_RUN_ID/model"
          export IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/pcos-model:$LATEST_RUN_ID"
          
          echo "Akan membuat dan push image dengan nama: $IMAGE_NAME"

          echo "--- Membangun Docker Image (MLflow Models) ---"
          mlflow models build-docker -m "$MODEL_URI" -n "$IMAGE_NAME" --enable-mlserver

          echo "--- Mendorong (Push) Docker Image ke Docker Hub ---"
          docker push "$IMAGE_NAME"

          echo "--- Menyimpan nama image untuk langkah selanjutnya (jika ada) ---"
          echo "$IMAGE_NAME" > image_name.txt