name: 3. CI Model Training

on:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Siapkan environment Conda
      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          
          activate-environment: workflow-ci
          
          environment-file: MLProject/conda.yaml
          python-version: '3.10'
          
      # Jalankan MLflow Project
      - name: Run MLflow Project
        shell: bash -l {0} 
        run: |
          
          mlflow run MLProject